spring:
  datasource:
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    minIdle: 5
    validationQuery: select 'x'
    initialSize: 5
    maxWait: 60000
    poolPreparedStatements: true
    filters: stat,wall,slf4j
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://47.95.238.195/quartz_test?useUnicode=true&characterEncoding=utf-8&useSSL=false&useAffectedRows=true
    username: root
    password: MaxRocky5721
    platform: mysql
    maxPoolPreparedStatementPerConnectionSize: 20
    testOnBorrow: false
    testWhileIdle: true
    minEvictableIdleTimeMillis: 30000
    timeBetweenEvictionRunsMillis: 60000
    testOnReturn: false
    driver-class-name: com.mysql.cj.jdbc.Driver
    maxActive: 300
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none